/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Control.ExecuteKopi;
import Model.Admin;
import Model.Kopi;
import java.util.ArrayList;

/**
 *
 * @author L. W. Aji
 */
public class FormDataKopi extends javax.swing.JFrame {

    Admin admin = new Admin();
    ExecuteKopi ek = new ExecuteKopi();
    ArrayList<Kopi> myKp = new ArrayList<>();
    /**
     * Creates new form FormDataPenjualan
     */
    public FormDataKopi() {
        initComponents();
        loadTabelKopi();
    }
    
    public FormDataKopi(Admin admin) {
        initComponents();
        loadTabelKopi();
        lblID.setText(admin.getId());
        lblNama.setText(admin.getNama());
    }
    
    private void loadTabelKopi() {
        myKp = ek.getAllKopi();
        Object[][] dtKp = new Object[myKp.size()][4];
        int mySize = 0;
        for (Kopi kopi : myKp) {
            dtKp[mySize][0] = kopi.getIdKopi();
            dtKp[mySize][1] = kopi.getJenisKopi();
            dtKp[mySize][2] = kopi.getStokKopi();
            dtKp[mySize][3] = kopi.getHargaKopi();
            mySize++;
        }
        tblKopi.setModel(new javax.swing.table.DefaultTableModel(dtKp,
                new String[]{"ID Kopi", "Jenis Kopi", "Stok", "Harga"}));

        jScrollPane1.setViewportView(tblKopi);
        
    }

    private void loadTabelKopiByJenis(String jenis) {
        myKp = ek.getKopiByJenis(jenis);
        Object[][] dtKp = new Object[myKp.size()][4];
        int mySize = 0;
        for (Kopi kopi : myKp) {
            dtKp[mySize][0] = kopi.getIdKopi();
            dtKp[mySize][1] = kopi.getJenisKopi();
            dtKp[mySize][2] = kopi.getStokKopi();
            dtKp[mySize][3] = kopi.getHargaKopi();
            mySize++;
        }
        tblKopi.setModel(new javax.swing.table.DefaultTableModel(dtKp,
                new String[]{"ID Kopi", "Jenis Kopi", "Stok", "Harga"}));

        jScrollPane1.setViewportView(tblKopi);
        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFilterJenis = new javax.swing.JTextField();
        btnCariKopi = new javax.swing.JButton();
        btnShowAllKopi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKopi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTambahStok = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Kopi");

        jLabel2.setText("Administrator");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("ID Admin          :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblID.setText("ID");
        jPanel3.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        lblNama.setText("Nama");
        jPanel3.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel10.setText("Nama Admin   :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cari Data Berdasarkan Jenis Kopi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(txtFilterJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        btnCariKopi.setText("Cari");
        btnCariKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKopiActionPerformed(evt);
            }
        });
        jPanel1.add(btnCariKopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 110));

        btnShowAllKopi.setText("Tampilkan Semua Data");
        btnShowAllKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllKopiActionPerformed(evt);
            }
        });
        jPanel7.add(btnShowAllKopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        tblKopi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKopi);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 480, 290));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Tambah Stok Kopi");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel2.add(txtTambahStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel2.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 110));

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenu)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(btnMenu))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllKopiActionPerformed
        // TODO add your handling code here:
        loadTabelKopi();
    }//GEN-LAST:event_btnShowAllKopiActionPerformed

    private void btnCariKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKopiActionPerformed
        // TODO add your handling code here:
        String jenis = txtFilterJenis.getText();
        loadTabelKopiByJenis(jenis);
    }//GEN-LAST:event_btnCariKopiActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        int row = tblKopi.getSelectedRow();
        int stok = Integer.parseInt(tblKopi.getValueAt(row, 2).toString());
        int jumlah = Integer.parseInt(txtTambahStok.getText());
        String id = tblKopi.getValueAt(row, 0).toString();
        ek.restoreStok(id, stok, jumlah);
        loadTabelKopi();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataKopi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariKopi;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnShowAllKopi;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTable tblKopi;
    private javax.swing.JTextField txtFilterJenis;
    private javax.swing.JTextField txtTambahStok;
    // End of variables declaration//GEN-END:variables
}
