/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Control.ExecuteDetailPenjualan;
import Control.ExecuteKopi;
import Control.ExecutePenjualan;
import Model.DetailPenjualan;
import Model.Kasir;
import Model.Kopi;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author L. W. Aji
 */
public class FormPenjualan extends javax.swing.JFrame {

    /**
     * Creates new form FormKopi
     */
    
    List<DetailPenjualan> listDetPenjualan = new ArrayList<>();
    int total = 0;
    Kasir kasir = new Kasir();
    
    public FormPenjualan() {
        initComponents();
        loadKopi();
    }
    
    public FormPenjualan(Kasir kasir){
        initComponents();
        loadKopi();   
        this.kasir = kasir;
        lblID.setText(kasir.getIdKasir());
        lblNama.setText(kasir.getNamaKasir());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKopi = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Jenis Kopi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setText("Jumlah");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 90, -1));

        jLabel3.setText("ons");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        btnTambah.setText("Tambah Barang");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        tblKopi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblKopi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 190));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel7.setText("Toko Kopi");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPenjualan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 190));

        jLabel4.setText("Total");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel5.setText("Rp");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        txtTotal.setEditable(false);
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 110, -1));

        jLabel6.setText(",00");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });
        jPanel2.add(btnBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jLabel8.setText("Total Pembelian");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("ID Kasir          :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblID.setText("ID");
        jPanel3.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        lblNama.setText("Nama");
        jPanel3.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel10.setText("Nama Kasir   :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadKopi() {
        ExecuteKopi ek = new ExecuteKopi();
        ArrayList<Kopi> myKopi = ek.getAllKopi();
        Object[][] dtKopi = new Object[myKopi.size()][4];
        int mySize = 0;
        for(Kopi kopi : myKopi) {
            dtKopi[mySize][0] = kopi.getIdKopi();
            dtKopi[mySize][1] = kopi.getJenisKopi();
            dtKopi[mySize][2] = kopi.getHargaKopi();
            dtKopi[mySize][3] = kopi.getStokKopi();
            mySize++;
        }
        tblKopi.setModel(new javax.swing.table.DefaultTableModel(dtKopi,
                new String[]{"ID", "Jenis", "Harga", "Stok"}));
        jScrollPane2.setViewportView(tblKopi);
    }
    
    private void loadTablePenjualan() {
        Object[][] objDetPnj = new Object[listDetPenjualan.size()][4];
        int column = 0;
        for(DetailPenjualan detPnj : listDetPenjualan) {
            objDetPnj[column][0] = detPnj.getJenisKopi();
            objDetPnj[column][1] = detPnj.getJumlah();
            objDetPnj[column][2] = detPnj.getHarga();
            objDetPnj[column][3] = detPnj.getTotal();
            column++;
        }
        tblPenjualan.setModel(new DefaultTableModel(objDetPnj,
                new String[]{"Jenis Kopi", "Jumlah", "Harga", "Total"}));
        jScrollPane1.setViewportView(tblPenjualan);
    }
    
    private void hitungTotalHarga() {
        total = 0;
        for(DetailPenjualan pnj : listDetPenjualan) {
            total = total + pnj.getTotal();
        }
        txtTotal.setText(String.valueOf(total));
    }
    
    private void addDetailPenjualan(DetailPenjualan pnj) {
        listDetPenjualan.add(pnj);
    }
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        DetailPenjualan detPnj = new DetailPenjualan();
        ExecuteKopi ek = new ExecuteKopi();
        int row = tblKopi.getSelectedRow();
        int stok = Integer.parseInt(tblKopi.getValueAt(row, 3).toString());
        int jumlah = Integer.parseInt(txtJumlah.getText());
        String id = tblKopi.getValueAt(row, 0).toString();
        if(jumlah <= stok) {
            detPnj.setIdKopi(id);
            detPnj.setJenisKopi(tblKopi.getValueAt(row, 1).toString());
            detPnj.setJumlah(jumlah);
            detPnj.setHarga(Integer.parseInt(tblKopi.getValueAt(row, 2).toString()));
            detPnj.getTotal();
            addDetailPenjualan(detPnj);
            loadTablePenjualan();
            hitungTotalHarga();
            ek.updateStok(id, stok, jumlah);
        }else {
            JOptionPane.showMessageDialog(rootPane, "Gagal Menambah Barang. "
                                          + "Jumlah melebihi stok yang tersedia");
            
        }
        loadKopi();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
        ExecutePenjualan ep = new ExecutePenjualan();
        ExecuteDetailPenjualan eDp = new ExecuteDetailPenjualan();
        String idPenjualan = ep.getNewIdPenjualan();
        if(ep.insertPenjualan(idPenjualan, kasir.getIdKasir(), 
                              kasir.getNamaKasir(), total) > 0) {
            for(DetailPenjualan detPnj : listDetPenjualan) {
                detPnj.setIdPenjualan(idPenjualan);
                eDp.insertDetailPenjualan(detPnj);
            }
            JOptionPane.showMessageDialog(this, "Transaksi Berhasil");
            txtTotal.setText("");
            listDetPenjualan.clear();
            loadTablePenjualan();
        } else {
            JOptionPane.showMessageDialog(this, "Transaksi Gagal,"
                            , null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FormAwal fa = new FormAwal();
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTable tblKopi;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
