/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Control.ExecuteDetailPenjualan;
import Model.Admin;
import Model.DetailPenjualan;
import java.util.ArrayList;

/**
 *
 * @author L. W. Aji
 */
public class FormDetailPenjualan extends javax.swing.JFrame {

    Admin admin = new Admin();
    ExecuteDetailPenjualan eDp = new ExecuteDetailPenjualan();
    ArrayList<DetailPenjualan> myDetPnj = new ArrayList<>();
    /**
     * Creates new form FormDataPenjualan
     */
    public FormDetailPenjualan() {
        initComponents();
        loadTabelDetailPenjualan();
    }
    
    public FormDetailPenjualan(Admin admin) {
        initComponents();
        loadTabelDetailPenjualan();
        lblID.setText(admin.getId());
        lblNama.setText(admin.getNama());
    }
    
    private void loadTabelDetailPenjualan() {
        myDetPnj = eDp.getDetailPenjualan();
        Object[][] dtPnj = new Object[myDetPnj.size()][6];
        int mySize = 0;
        for (DetailPenjualan detPnj : myDetPnj) {
            dtPnj[mySize][0] = detPnj.getIdPenjualan();
            dtPnj[mySize][1] = detPnj.getIdKopi();
            dtPnj[mySize][2] = detPnj.getJenisKopi();
            dtPnj[mySize][3] = detPnj.getJumlah();
            dtPnj[mySize][4] = detPnj.getHarga();
            dtPnj[mySize][5] = detPnj.getTotal();
            mySize++;
        }
        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(dtPnj,
                new String[]{"ID Penjualan", "ID Kopi", "Jenis Kopi", "Jumlah", 
                             "Harga", "Total"}));
        jScrollPane1.setViewportView(tblPenjualan); 
    } 
    
    private void loadTabelDetailPenjualanByIdPenjualan(String id) {
        myDetPnj = eDp.getDetailPenjualanByIdPenjualan(id);
        Object[][] dtPnj = new Object[myDetPnj.size()][6];
        int mySize = 0;
        for (DetailPenjualan detPnj : myDetPnj) {
            dtPnj[mySize][0] = detPnj.getIdPenjualan();
            dtPnj[mySize][1] = detPnj.getIdKopi();
            dtPnj[mySize][2] = detPnj.getJenisKopi();
            dtPnj[mySize][3] = detPnj.getJumlah();
            dtPnj[mySize][4] = detPnj.getHarga();
            dtPnj[mySize][5] = detPnj.getTotal();
            mySize++;
        }
        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(dtPnj,
                new String[]{"ID Penjualan", "ID Kopi", "Jenis Kopi", "Jumlah", 
                             "Harga", "Total"}));
        jScrollPane1.setViewportView(tblPenjualan); 
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFilterId = new javax.swing.JTextField();
        btnCariDetail = new javax.swing.JButton();
        btnShowAllDetail = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        btnMenu = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Detail Penjualan");

        jLabel2.setText("Administrator");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("ID Admin          :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblID.setText("ID");
        jPanel3.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        lblNama.setText("Nama");
        jPanel3.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel10.setText("Nama Admin   :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cari Data Berdasarkan ID Penjualan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(txtFilterId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        btnCariDetail.setText("Cari");
        btnCariDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDetailActionPerformed(evt);
            }
        });
        jPanel1.add(btnCariDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 110));

        btnShowAllDetail.setText("Tampilkan Semua Data");
        btnShowAllDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllDetailActionPerformed(evt);
            }
        });
        jPanel7.add(btnShowAllDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPenjualan);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 480, 290));

        btnMenu.setText("Menu");

        btnMenu1.setText("Menu");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenu1)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnMenu)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(btnMenu1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnMenu)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllDetailActionPerformed
        // TODO add your handling code here:
        loadTabelDetailPenjualan();
    }//GEN-LAST:event_btnShowAllDetailActionPerformed

    private void btnCariDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDetailActionPerformed
        // TODO add your handling code here:
        String id = txtFilterId.getText();
        loadTabelDetailPenjualanByIdPenjualan(id);
    }//GEN-LAST:event_btnCariDetailActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDetailPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDetailPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDetailPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDetailPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDetailPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariDetail;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnShowAllDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtFilterId;
    // End of variables declaration//GEN-END:variables
}
